include( CMakeFindDependencyMacro )
find_dependency( nlohmann_json )
find_dependency( Boost )
find_dependency( uriparser )
find_dependency( fmt )
find_dependency( spdlog )
include( ${CMAKE_CURRENT_LIST_DIR}/consulcppTargets.cmake )
